const Data = [
    { name: 'Mercy', description: 'A is for Apple 🍎', color: '#FF6B6B' },
    { name: 'Alex', description: 'B is for Ball 🎾', color: '#6BCB77' },
    { name: 'Glory', description: 'C is for Cat 🐱', color: '#4D96FF' },
    { name: 'Mercy', description: 'D is for Dog 🐶', color: '#FFD93D' },
    { name: 'Mercy', description: 'E is for Elephant 🐘', color: '#9D4EDD' },
    { name: 'Mercy', description: 'F is for Fish 🐟', color: '#F38BA0' },
    { name: 'Mercy', description: 'G is for Grapes 🍇', color: '#7F27FF' },
    { name: 'Mercy', description: 'H is for Hat 🎩', color: '#00C897' },
    { name: 'Mercy', description: 'I is for Ice Cream 🍦', color: '#FDCB6E' },
    { name: 'Mercy', description: 'J is for Jelly 🪼', color: '#FF8FAB' },
    { name: 'Mercy', description: 'K is for Kite 🪁', color: '#0F4C75' },
    { name: 'Mercy', description: 'L is for Lion 🦁', color: '#F9A825' },
    { name: 'Mercy', description: 'M is for Monkey 🐵', color: '#F67280' },
    { name: 'Mercy', description: 'N is for Nest 🪺', color: '#344955' },
    { name: 'Mercy', description: 'O is for Owl 🦉', color: '#FFA500' },
    { name: 'Mercy', description: 'P is for Penguin 🐧', color: '#2A2A72' },
    { name: 'Mercy', description: 'Q is for Queen 👑', color: '#845EC2' },
    { name: 'Mercy', description: 'R is for Rainbow 🌈', color: '#E91E63' },
    { name: 'Mercy', description: 'S is for Sun ☀️', color: '#FFD700' },
    { name: 'Mercy', description: 'T is for Turtle 🐢', color: '#2ECC71' },
    { name: 'Mercy', description: 'U is for Umbrella ☔️', color: '#0096C7' },
    { name: 'Mercy', description: 'V is for Violin 🎻', color: '#6A0572' },
    { name: 'Mercy', description: 'W is for Whale 🐋', color: '#3E92CC' },
    { name: 'Mercy', description: 'X is for Xylophone 🎶', color: '#FF6F61' },
    { name: 'Mercy', description: 'Y is for Yak 🐂', color: '#B56576' },
    { name: 'Mercy', description: 'Z is for Zebra 🦓', color: '#222831' },
  ];

  export default Data;
  